window.FixedCostContent = {
  articles: [
    {
      title: "スマホ代が高い原因と見直し方",
      category: "スマホ代",
      href: "article-smartphone-cost.html",
      description: "プラン、端末代、オプション、家族回線を分けて確認します。",
      tags: ["smartphone", "mobile"],
    },
    {
      title: "スマホ代が月1万円は高い？見直す前に確認すること",
      category: "スマホ代 月1万円",
      href: "article-smartphone-10000-yen.html",
      description: "通信料金、端末代、オプションを分けて原因を整理します。",
      tags: ["smartphone", "mobile"],
    },
    {
      title: "ネット回線が月6,000円は高い？確認するポイント",
      category: "ネット回線",
      href: "article-internet-6000-yen.html",
      description: "基本料金、ルーター代、オプション、スマホとの組み合わせを確認します。",
      tags: ["internet", "wifi"],
    },
    {
      title: "電気代・ガス代が高いときに確認すること",
      category: "光熱費",
      href: "article-utilities-cost.html",
      description: "契約プランや家族構成による負担を見える化します。",
      tags: ["utilities", "energy"],
    },
    {
      title: "家族の電気代が高いときに確認すること",
      category: "家族 光熱費",
      href: "article-family-electricity-cost.html",
      description: "我慢で削る前に、季節要因や契約プランを確認します。",
      tags: ["utilities", "family"],
    },
    {
      title: "サブスクを解約できない人向けの整理方法",
      category: "サブスク",
      href: "article-subscription-cancel.html",
      description: "利用頻度で残すものと見直すものを分ける方法です。",
      tags: ["subscription"],
    },
    {
      title: "使っていないサブスクを整理するチェックリスト",
      category: "サブスク整理",
      href: "article-unused-subscription-cancel.html",
      description: "動画、音楽、学習、アプリ、クラウドを利用頻度で整理します。",
      tags: ["subscription"],
    },
    {
      title: "子育て世帯の固定費を見直す順番",
      category: "子育て 固定費",
      href: "article-family-fixed-cost.html",
      description: "教育費を守りながら、家族全体の固定費を整えます。",
      tags: ["family", "childcare"],
    },
    {
      title: "子育て世帯でお金が残らないときの固定費チェック",
      category: "子育て 家計",
      href: "article-family-money-left.html",
      description: "家族全体で整えやすい固定費を見つけます。",
      tags: ["family", "childcare"],
    },
    {
      title: "家賃・住宅ローンが家計を圧迫しているときの見方",
      category: "住宅固定費",
      href: "article-housing-fixed-cost.html",
      description: "住まいの安心を守りながら、固定費全体で重さを確認します。",
      tags: ["housing", "mortgage", "family"],
    },
    {
      title: "火災保険は更新前に比較した方がいい？確認ポイント",
      category: "火災保険",
      href: "article-fire-insurance-check.html",
      description: "補償内容、保険期間、建物・家財、地震保険を確認します。",
      tags: ["housing", "insurance"],
    },
    {
      title: "住宅ローンの見直しはいつ考える？固定費として確認するポイント",
      category: "住宅ローン",
      href: "article-mortgage-review.html",
      description: "金利、残期間、借入残高、借り換え費用を整理します。",
      tags: ["housing", "mortgage"],
    },
    {
      title: "家族のスマホ代を見直す順番",
      category: "家族 スマホ代",
      href: "article-family-smartphone-saving.html",
      description: "家族回線、端末代、子どものスマホ代を分けて確認します。",
      tags: ["smartphone", "mobile", "family"],
    },
    {
      title: "電気・ガスの切り替え前に確認すること",
      category: "電気 ガス",
      href: "article-electric-gas-switching.html",
      description: "契約会社、プラン、使用量を確認します。",
      tags: ["utilities", "energy"],
    },
    {
      title: "光回線と工事なしWi-Fi、どちらを選ぶ？",
      category: "ネット回線",
      href: "article-home-wifi-vs-fiber.html",
      description: "固定費、使い方、家族構成からネット回線を比較します。",
      tags: ["internet", "wifi"],
    },
    {
      title: "見直しやすい固定費ランキング",
      category: "固定費 見直し",
      href: "article-fixed-cost-review-ranking.html",
      description: "スマホ代、サブスク、光熱費、ネット回線、住宅固定費の順番を整理します。",
      tags: ["budget", "smartphone", "subscription", "utilities"],
    },
    {
      title: "保険料が高いと感じたときに確認すること",
      category: "保険料",
      href: "article-insurance-premium-high.html",
      description: "保障内容と家計のバランスを確認します。",
      tags: ["insurance", "family"],
    },
    {
      title: "毎月お金が残らない人の固定費チェックリスト",
      category: "家計チェック",
      href: "article-money-left-checklist.html",
      description: "家計簿が苦手でも確認しやすい固定費の順番です。",
      tags: ["budget"],
    },
  ],
};
